@base_url = http://localhost:5001

GET {{base_url}}
Accept: application/json

<> 2024-12-05T121258.200.json

###
GET {{base_url}}/pets

###
POST {{base_url}}/pets
Content-Type: application/json

{
  "id": "string",
  "name": "string",
  "description": "string",
  "breed": {
    "name": "string",
    "description": "string"
  },
  "color": {
    "general": "string",
    "body": "string",
    "face": "string",
    "tail": "string",
    "legs": "string"
  }
}

<> 2024-12-05T121248.200.json
<> 2024-12-05T110555.200.json
<> 2024-12-05T110414.200.json
<> 2024-12-05T100511.200.html

###